### ISSUE TITLE
Problems with platform-specific artifacts and native app images

### ISSUE THREAD

**Issue by io7m** [io7m-com/montarre#22]
LWJGL can't currently find its own native libraries in the Rocaro demo when a native app image is produced:

```
[rm@workstation01 rocaro-demo]$ _JAVA_OPTIONS="-Dorg.lwjgl.util.Debug=true" ./bin/rocaro-demo demo displays
Picked up _JAVA_OPTIONS: -Dorg.lwjgl.util.Debug=true
[LWJGL] Version: 3.3.5-snapshot+2
	 OS: Linux v6.12.1-arch1-1
	JRE: Linux amd64 22.0.2
	JVM: OpenJDK 64-Bit Server VM v22.0.2+9 by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
	Module: org.lwjgl
	linux/x64/org/lwjgl/liblwjgl.so not found in java.library.path=:/home/rocaro/git/com.github/io7m/rocaro.packaging/target/output/rocaro-demo/lib/app:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	liblwjgl.so not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.Library.loadSystem(Library.java:174)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.Library.loadSystem(Library.java:64)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.Library.<clinit>(Library.java:52)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryStack.create(MemoryStack.java:96)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryStack.create(MemoryStack.java:85)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryStack.create(MemoryStack.java:74)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source)
	at java.base/java.lang.ThreadLocal.setInitialValue(Unknown Source)
	at java.base/java.lang.ThreadLocal.get(Unknown Source)
	at java.base/java.lang.ThreadLocal.get(Unknown Source)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:899)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:908)
	at org.lwjgl@3.3.5-snapshot+2/org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at com.io7m.rocaro.vanilla@0.0.1-SNAPSHOT/com.io7m.rocaro.vanilla.internal.RCGLFWFacade.<clinit>(RCGLFWFacade.java:53)
	at com.io7m.rocaro.vanilla@0.0.1-SNAPSHOT/com.io7m.rocaro.vanilla.RCDisplays.displays(RCDisplays.java:49)
	at com.io7m.rocaro.demo@0.0.1-SNAPSHOT/com.io7m.rocaro.demo.internal.RCDemoDisplays.onExecute(RCDemoDisplays.java:62)
	at com.io7m.quarrel.core@1.6.1/com.io7m.quarrel.core.internal.QCommandContext.execute(QCommandContext.java:207)
	at com.io7m.quarrel.core@1.6.1/com.io7m.quarrel.core.QApplicationType.run(QApplicationType.java:94)
	at com.io7m.rocaro.demo@0.0.1-SNAPSHOT/com.io7m.rocaro.demo.RCDemoMain.run(RCDemoMain.java:144)
	at com.io7m.rocaro.demo@0.0.1-SNAPSHOT/com.io7m.rocaro.demo.RCDemoMain.mainExitless(RCDemoMain.java:119)
	at com.io7m.rocaro.demo@0.0.1-SNAPSHOT/com.io7m.rocaro.demo.RCDemoMain.main(RCDemoMain.java:104)
```

Because this is a platform-specific app image, all platform-specific libraries should be placed directly into `lib/app/mods` instead of `lib/app/mods/x86_64/linux`.

**Comment by io7m** [comment]
Done.
